import type { Metadata } from "next";
import Header from "./layout/Header";
import Footer from "./layout/Footer";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ko">
			<body>
				<div className="flex flex-col min-h-screen w-[90%] max-w-[1400px] mx-auto">
					<Header />
					<main className="flex-grow">{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
